name       : openclonk
version    : 8.1
release    : 4
source     :
    - https://github.com/openclonk/openclonk/archive/v8.1.tar.gz : fea0cd473334c9adf74a8930c42c78b8c2eb9255e267976a700910e07d2a0506
license    :
    - ISC
    - CC-BY-3.0
component  : games.action
summary    : OpenClonk is a free multiplayer action game in which you control clonks,
    small but witty and nimble humanoid beings. The game is mainly about mining, settling
    and fast-paced melees.
description: |
    OpenClonk is a free multiplayer action game in which you control clonks, small but witty and nimble humanoid beings. The game is mainly about mining, settling and fast-paced melees.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(Qt5OpenGL)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(xrandr)
    - miniupnpc-devel
    - readline-devel
setup      : |
    %patch -p1 < $pkgfiles/fix-games.patch
    %cmake
build      : |
    %make
install    : |
    %make_install
